driver.class: driver.java sinAPTik.class
	@javac -sourcepath . -cp ftp4j-1.7.2.jar driver.java
sinAPTik.class: sinAPTik.java
	@javac -cp ftp4j-1.7.2.jar sinAPTik.java
run:
	@java driver libcommons-parent-java_22-2_all.deb
clean:
	@rm *.class
